# Generates app/src/main/cpp/native-lib.cpp with XOR-obfuscated secrets.
# Edit the $Secrets table below, then run:  .\generate_xor_cpp.ps1
param(
    [string]$OutFile = (Join-Path $PSScriptRoot "..\src\main\cpp\native-lib.cpp")
)

$Secrets = [ordered]@{
    supabaseUrl        = "https://unnjvvfkpgnuojepgtmi.supabase.co"
    supabaseAnonKey    = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVubmp2dmZrcGdudW9qZXBndG1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAzNDY4ODQsImV4cCI6MjEwNTkyMjg4NH0.6P48Fg4UuwEwTJeNILw_CBZ2Gq83ai7QUe6NZbdO4F0"
    supabaseServiceKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVubmp2dmZrcGdudW9qZXBndG1pIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc5MDM0Njg4NCwiZXhwIjoyMTA1OTIyODg0fQ.QGdWZ5bTrKoAF2EdqF7D2UM2DKgVlbVe84m69HsC6jQ"
    imagekitPrivateKey = "private_YbKy+CIKMdJlBXsPj/f9bR1XylE="
    appName            = "MITRC"
}

$rng = [System.Random]::new()
$sb = [System.Text.StringBuilder]::new()

[void]$sb.AppendLine("#include <jni.h>")
[void]$sb.AppendLine("#include <string>")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("// GENERATED BY scripts/generate_xor_cpp.ps1 - DO NOT EDIT BY HAND")
[void]$sb.AppendLine("")

foreach ($name in $Secrets.Keys) {
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($Secrets[$name])
    $key = $rng.Next(1, 255)
    $arr = ($bytes | ForEach-Object { "0x{0:X2}" -f ($_ -bxor $key) }) -join ", "
    [void]$sb.AppendLine("static const unsigned char enc_$name[] = { $arr };")
    [void]$sb.AppendLine("static const int len_$name = $($bytes.Length);")
    [void]$sb.AppendLine("static const unsigned char key_$name = $key;")
    [void]$sb.AppendLine("")
}

[void]$sb.AppendLine("static std::string xor_decode(const unsigned char* data, int len, unsigned char key) {")
[void]$sb.AppendLine("    std::string out;")
[void]$sb.AppendLine("    out.reserve(len);")
[void]$sb.AppendLine("    for (int i = 0; i < len; i++) {")
[void]$sb.AppendLine("        out.push_back(static_cast<char>(data[i] ^ key));")
[void]$sb.AppendLine("    }")
[void]$sb.AppendLine("    return out;")
[void]$sb.AppendLine("}")
[void]$sb.AppendLine("")

foreach ($name in $Secrets.Keys) {
    [void]$sb.AppendLine("extern `"C`" JNIEXPORT jstring JNICALL")
    [void]$sb.AppendLine("Java_com_mitrc_ac_in_utils_NativeUtils_get$($name.Substring(0,1).ToUpper() + $name.Substring(1))(JNIEnv* env, jobject) {")
    [void]$sb.AppendLine("    return env->NewStringUTF(xor_decode(enc_$name, len_$name, key_$name).c_str());")
    [void]$sb.AppendLine("}")
    [void]$sb.AppendLine("")
}

New-Item -ItemType Directory -Force -Path (Split-Path $OutFile) | Out-Null
[System.IO.File]::WriteAllText($OutFile, $sb.ToString())
Write-Host "Wrote $OutFile"
